package cn.ok.examples.helloworld

import cn.ok.domains.Message;

global java.util.List list;

rule "Hello World"
    dialect "mvel"
    when
        m : Message( status == Message.HELLO, message : message )
    then
        System.out.println( "0: " + message );
        modify( m ) { message = "Goodbye cruel world", status = Message.GOODBYE };
end

rule "Good Bye"
    dialect "java"
    when
        Message( status == Message.GOODBYE, message : message )
    then
        System.out.println( "1: " + message );
end
