package cn.ok.examples.helloworld

import cn.ok.domains.Message;

global java.util.List list

rule "Hello World"
    dialect "mvel"
    when
        m : Message( status == Message.HELLO, message : message )
    then
        list.add("Hello World");
        System.out.println( "0: " + message );

        // 修改 message 对象，此修改在规则外部依然生效。
        modify( m ) { message = "Goodbye cruel world", status = Message.GOODBYE };
end

rule "Good Bye"
    dialect "java"
    when
        Message( status == Message.GOODBYE, message : message )
    then
        list.add("Good Bye");
        System.out.println( "1: " + message );
end
